services:
  db:
    image: postgres:15
    container_name: trivia_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trivia
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/

  web:
    build: .
    container_name: trivia_app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
